### ISSUE TITLE
Not working with Catalina

### ISSUE THREAD

**Issue by emwok** [thomasrutkowski/vpnfix#2]
Have you experienced these same issues with Catalina?  I'm running 10.15.4 on a new machine and all of a sudden, this previous fix isn't working again.  Are you aware of any updates that would break this VPN fix?  I've been using this fix for years on my previous Sierra 10.12.6 machine and now, the exact same fix isn't working and I'm getting dropped after 45 minutes again...

Any help would be greatly appreciated!

**Comment by sundski** [comment]
I believe Apple fixed the hard limit timeout in one of the minor versions of Snow leopard, So this fix shouldn't be needed at all unless you are running a really old system.

I no longer use either the built in vpn in osx or any IPSEC-tunnels, so I'm afraid I can't be of much help other than recommending that you revert the racoon.conf file.
